
-------------------------------------------------------------
| Z-set version 9.0.1            compiled 2018-12-11 by val |
|                                SVN revision:17246M        |
|                                                           |
| MINES ParisTech                www.mines-paristech.fr     |
| ONERA                          www.onera.fr               |
|                                                           |
| Website                        www.zset-software.com      |
-------------------------------------------------------------

Process Id (PID)         : 38308
Process parent Id (PPID) : 30812
Hostname                 : rosetta-viz01

Problem name: cube

============================================================
Zebulon 9.0 checking out license for fem

 checkout of license 98/500 for product:fem
 license expires in 201 days
============================================================

key: init_dof_value
key: mesh
key: resolution
key: bc
key: material
key: table
key: output

Done loading cube.geof
Number of global DOFs: 676

Number of elements              : 625
Total number of dof             : 676
Estimated memory needed (KB)    : 407

seq:  1 incr:  1 dt:200      t:200         
 iter:  1 | R |/| Fext |= 1.761e-15  | Fext |=117239.

seq:  1 incr:  2 dt:200      t:400         
 iter:  1 | R |/| Fext |= 1.050e-15  | Fext |=53774.6

seq:  1 incr:  3 dt:200      t:600         
 iter:  1 | R |/| Fext |= 1.347e-15  | Fext |=40866.1

seq:  1 incr:  4 dt:200      t:800         
 iter:  1 | R |/| Fext |= 1.588e-15  | Fext |=34199.9

seq:  1 incr:  5 dt:200      t:1000        
 iter:  1 | R |/| Fext |= 1.646e-15  | Fext |=29824.5


++++++++++++++++++++++  end of Z++  ++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                     CPU time  Wall-clock
  Time CPU Total                  =      0.16      0.1941
  Time Problem Loading            =      0.01      0.0067
  Time Loading nodes              =         0    0.002105
  Time Loading elements           =         0    0.002625
  Time Read nset                  =         0   5.078e-05
  Time Read bset                  =         0    0.000155
  Time Mesh connections           =         0    0.000232
  Time Mesh create dof            =         0   0.0004299
  Time Sparse matrix profile      =         0   0.0004091
  Time Mumps profile              =         0    0.001121
  Time Mumps analyze              =         0    0.000855
  Time Output                     =      0.03     0.03123
  Time Execution                  =      0.13      0.1471
  Time Compute_internal_reac      =       0.1     0.09433
  Time Mumps solver               =         0     0.01177
  Time Mumps factorization        =         0    0.008415
  Time Mumps solutions            =         0      0.0031
  Mumps analyze calls             =  1
  Total Iterations                =  5
  Compute_internal_reac calls     =  10
  Mumps factorization calls       =  5
  Mumps solutions calls           =  5
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

