
-------------------------------------------------------------
| Z-set version 9.0.1            compiled 2018-12-11 by val |
|                                SVN revision:17246M        |
|                                                           |
| MINES ParisTech                www.mines-paristech.fr     |
| ONERA                          www.onera.fr               |
|                                                           |
| Website                        www.zset-software.com      |
-------------------------------------------------------------

Process Id (PID)         : 38257
Process parent Id (PPID) : 30812
Hostname                 : rosetta-viz01

Problem name: cube

============================================================
Zebulon 9.0 checking out license for fem

 checkout of license 98/500 for product:fem
 license expires in 201 days
============================================================

key: init_dof_value
key: mesh
key: resolution
key: bc
key: material
key: table
key: output

Done loading cube.geof
Number of global DOFs: 676

Number of elements              : 625
Total number of dof             : 676
Estimated memory needed (KB)    : 407

seq:  1 incr:  1 dt:200      t:200         
 iter:  1 | R |/| Fext |= 7.876e-16  | Fext |=91906.9

seq:  1 incr:  2 dt:200      t:400         
 iter:  1 | R |/| Fext |= 9.705e-16  | Fext |=50617.0

seq:  1 incr:  3 dt:200      t:600         
 iter:  1 | R |/| Fext |= 1.186e-15  | Fext |=38411.6

seq:  1 incr:  4 dt:200      t:800         
 iter:  1 | R |/| Fext |= 1.414e-15  | Fext |=32174.6

seq:  1 incr:  5 dt:200      t:1000        
 iter:  1 | R |/| Fext |= 1.628e-15  | Fext |=28124.4


++++++++++++++++++++++  end of Z++  ++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                     CPU time  Wall-clock
  Time CPU Total                  =      0.16      0.1841
  Time Problem Loading            =      0.01    0.006616
  Time Loading nodes              =         0     0.00204
  Time Loading elements           =         0    0.002469
  Time Read nset                  =         0   5.364e-05
  Time Read bset                  =      0.01   0.0001719
  Time Mesh connections           =         0   0.0002062
  Time Mesh create dof            =         0   0.0004191
  Time Sparse matrix profile      =         0   0.0003741
  Time Mumps profile              =         0      0.0011
  Time Mumps analyze              =         0   0.0008612
  Time Output                     =      0.02     0.03037
  Time Execution                  =      0.13      0.1416
  Time Compute_internal_reac      =      0.09     0.09441
  Time Mumps solver               =      0.01     0.01165
  Time Mumps factorization        =      0.01    0.008311
  Time Mumps solutions            =         0     0.00315
  Mumps analyze calls             =  1
  Total Iterations                =  5
  Compute_internal_reac calls     =  10
  Mumps factorization calls       =  5
  Mumps solutions calls           =  5
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

