image: python:3.7-alpine

variables:
  MYPROJECT : 'mordicus'

stages:
  - doc
  - test
  - deploy

doc:
  stage: doc
  image: python:3.7-alpine
  before_script:
    - apk add build-base texlive texmf-dist-latexextra
    - pip install -U sphinx sphinxcontrib-bibtex
  script:
    - export PYTHONPATH=$PWD/../basic-tools/src:$PYTHONPATH
    - mkdir -p pages/doc
    - cd - && cd doc/
    - make latexpdf
    - cd - && cd src/poc-1/doc
    - make html
    - cd - && mv doc/build/latex pages/doc/latex
    - cd - && mv src/poc-1/doc/_build/html pages/doc/html && cd -
  artifacts:
    name: "Documentation"
    paths:
      - pages/doc

.test:
  stage: test
  image: python:3.7
  before_script:
    - apt-get update
    - apt-get install -y python3-venv gcc python3-dev libopenmpi-dev make
    - pip install --upgrade pip
    - export BASICTOOLS_BUILD_CYTHON=False
    - pip install -r ./src/poc-1/requirements.txt
    - export PYTHONPATH=$PWD/../basic-tools/src:$PYTHONPATH

poc-1:
  extends: .test
  script:
    - export PYTHONPATH=$PWD/src/poc-1/src:$PYTHONPATH
    - mkdir -p pages/coverageReportCore
    - cd src/poc-1/tests/Core && pytest --cov=../../src/Mordicus/Core --cov-report=html:../../../../pages/coverageReportCore && cd -
    - cd src/poc-1/tests/Modules/Phimeca && pytest && cd -
    - cd pages/coverageReportCore && grep pc_cov index.html
  coverage: '/pc_cov">([0-9]+\.?[0-9]+?%)/'
  artifacts:
    name: "CoverageCore"
    paths:
      - pages/coverageReportCore


pages:
  image: alpine:latest
  stage: deploy
  dependencies:
    - poc-1
    - doc
  script:
    - mv pages/ public/
  artifacts:
    name: "WebSite"
    paths:
      - public    

