image: python:3.7-alpine

variables:
  MYPROJECT : 'mordicus'

stages:
  - doc
  - test
  - deploy

doc:
  stage: doc
  image: python:3.7-alpine
  before_script:
    - apk add build-base texlive texmf-dist-latexextra
    - pip install -U sphinx sphinxcontrib-bibtex
  script:
    - export PYTHONPATH=$PWD/../basic-tools/src:$PYTHONPATH
    - mkdir -p public/doc
    - cd src/poc-1/doc
    - make html
    - mv _build/html ../../../public/doc/html && cd -
    - cd doc/
    - make latexpdf
    - mv build/latex ../public/doc/latex && cd -
  artifacts:
    name: "Documentation"
    paths:
      - public/doc

.test:
  stage: test
  image: python:3.7
  before_script:
    - apt-get update
    - apt-get install -y python3-venv gcc python3-dev libopenmpi-dev make
    - pip install --upgrade pip
    - export BASICTOOLS_BUILD_CYTHON=False
    - pip install -r ./src/poc-1/requirements.txt
    - export PYTHONPATH=$PWD/../basic-tools/src:$PYTHONPATH

poc-1:
  extends: .test
  script:
    - export PYTHONPATH=$PWD/src/poc-1/src:$PYTHONPATH
    - mkdir -p public/coverageReportCore
    - cd src/poc-1/tests/Core && pytest --cov=../../src/Mordicus/Core --cov-report=html:../../../../public/coverageReportCore && cd -
    - cd src/poc-1/tests/Modules/Phimeca && pytest && cd -
    - cd public/coverageReportCore && grep pc_cov index.html
  coverage: '/pc_cov">([0-9]+\.?[0-9]+?%)/'
  artifacts:
    name: "CoverageCore"
    paths:
      - public/coverageReportCore


pages:
  image: alpine:latest
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    name: "WebSite"
    paths:
      - public    

