variables:
    GIT_SSL_NO_VERIFY: "1"
    MYPROJECT : 'mordicus'

stages:
    - test


coverage:
    stage: test
    tags:
       - mordicus
    script:
        - echo $PYTHONPATH
    coverage: '/pc_cov">([0-9]+\.?[0-9]+?%)/'
    artifacts:
        name: "Coverage"
        paths:
            - public/coverage


pages:
    stage: deploy
    tags:
        - genericROM
    script:
        - pwd
    artifacts:
        name: "WebSite"
        paths:
            - public
