
:feelpp: Feel++
:cpp: C++
// # :toc: macro
:toclevels: 2
:stem: latexmath
:uri-rel-file-base: link:
:uri-rel-tree-base: link:
ifdef::env-site[]
:uri-rel-file-base: {uri-repo}/blob/develop/
:uri-rel-tree-base: {uri-repo}/tree/develop/
endif::[]
ifndef::env-github[:icons: font]
ifdef::env-github,env-gitlab[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:!toc-title:
:badges:
endif::[]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
// URIs:
:uri-org: https://github.com/feelpp
:uri-repo: {uri-org}/feelpp
:uri-www: http://www.feelpp.org
:uri-project: https://feelpp.github.io/mordicus/
:uri-docs: {uri-project}/
:uri-news: {uri-www}/news
:uri-manpage: {uri-project}/man/asciidoctor
:uri-help-base: https://help.github.com/articles
:uri-contribute: {uri-rel-file-base}CONTRIBUTING.adoc
:uri-license: {uri-rel-file-base}LICENSE.adoc
:uri-issues: {uri-repo}/issues
:uri-contributors: {uri-repo}/graphs/contributors
:uri-fork-help: {uri-help-base}/fork-a-repo
:uri-branch-help: {uri-fork-help}#create-branches
:uri-pr-help: {uri-help-base}/using-pull-requests
:uri-gist: https://gist.github.com
:uri-freesoftware: https://www.gnu.org/philosophy/free-sw.html

ifdef::badges[]
image:https://img.shields.io/github/watchers/feelpp/mordicus?color=009688&logo=Bilibili&logoColor=white&style=flat-square[link=https://github.com/feelpp/mordicus/watchers]
image:https://img.shields.io/github/contributors/feelpp/feelpp?logo=Draugiem.lv&logoColor=white&color=009688&style=flat-square[link=https://github.com/feelpp/mordicus/graphs/contributors]
image:https://img.shields.io/github/repo-size/feelpp/mordicus?color=009688&style=flat-square&logo=Hack The Box&logoColor=white[link=https://github.com/feelpp/mordicus]
image:https://img.shields.io/badge/python-3.8|3.9-blue?&logo=python&logoColor=yellow[]
endif::[]

= Mordicus


A project by **Safran Tech**, **EDF**, **Mines Paris Tech**, **CADLM**, **CT Ingénierie**, **Transvalor SA**, **Scilab Enterprises**, **Phiméca**, **Cemosis**, **Sorbonnes Universités**.

== Requirements

=== Python

- cmake >= 3.21 (to enable cmake presets)
- python 3.8 or 3.9
- pip

[source,sh]
----
pip -r src/poc-1/requirements.txt
export PYTHONPATH=$PWD/src/poc-1/src:$HOME/.local/lib/python3.8/site-packages:$PYTHONPATH
----

=== {cpp}

- cmake
- g++ or clang
- python3.8 or 3.9 python3-dev
- pybind11
- [optional] {feelpp}
- [optional] openturns
- [optional] basictools

.Install the following packages for Python and {cpp} on Debian/bullseye:
[source,sh]
----
sudo apt-get -y install apt-transport-https ca-certificates gnupg software-properties-common wget
sudo apt-get install cmake g++ python3-dev python3-pip python3-pybind11
apt-get -y install python3-pip python3-venv gcc clang python3-dev libopenmpi-dev make libeigen3-dev python3-lxml 
sudo add-apt-repository  'deb http://deb.debian.org/debian bullseye-backports main'
sudo apt-get -y install -t bullseye-backports  cmake
----

.Configure, compile and tests the {cpp} and Python codes
[source,shell]
----
cmake --preset install <1>
cmake --build --preset install <2>
ctest --preset install <3>
cd src/poc-1/tests && pytest --ignore Modules/Safran <4>
----
<1> configure cmake with `install` preset
<2> build the project with `install` preset
<3> run ctest with `install` preset
<4> run pytest 


==== (Optional) {feelpp}

.install on a bullseye machine (see link:https://docs.feelpp.org/user/latest/install/index.html[{feelpp} docs] for other options )
[source,shell]
----
add-apt-repository  'deb [trusted=yes] http://apt.feelpp.org/debian/bullseye bullseye latest'
wget -O - http://apt.feelpp.org/apt.gpg | apt-key add - && apt-get update 
apt -y install python3-feelpp 
----

