
-------------------------------------------------------------
| Z-set version 9.0.1            compiled 2018-12-11 by val |
|                                SVN revision:17246M        |
|                                                           |
| MINES ParisTech                www.mines-paristech.fr     |
| ONERA                          www.onera.fr               |
|                                                           |
| Website                        www.zset-software.com      |
-------------------------------------------------------------

Process Id (PID)         : 1369
Process parent Id (PPID) : 36216
Hostname                 : rosetta-viz01

Problem name: cube

============================================================
Zebulon 9.0 checking out license for fem

 checkout of license 1/500 for product:fem
 license expires in 202 days
============================================================

key: mesh
key: resolution
key: linear_solver
key: bc
key: table

Warning; CYCLIC_TABLE topload is not cyclic (beg_val=0.00000, end_val=-500.000)

key: output
key: material

Done loading cube.geof
Number of global DOFs: 1029

Number of elements              : 216
Total number of dof             : 1029
Estimated memory needed (MB)    : 4

cyc:  1 seq:  1 incr:  1 dt:0.2      t:0.2         
       iter:  1 | R |/| Fext |= 4.481e-15  | Fext |=210.375

cyc:  1 seq:  1 incr:  2 dt:0.2      t:0.4         
       iter:  1 | R |/| Fext |= 8.294e-16  | Fext |=199.003

cyc:  1 seq:  1 incr:  3 dt:0.2      t:0.6         
       iter:  1 | R |/| Fext |= 1.060e-15  | Fext |=187.631

cyc:  1 seq:  1 incr:  4 dt:0.2      t:0.8         
       iter:  1 | R |/| Fext |= 1.005e-15  | Fext |=176.260

cyc:  1 seq:  1 incr:  5 dt:0.2      t:1           
       iter:  1 | R |/| Fext |= 9.186e-16  | Fext |=164.888

cyc:  1 seq:  1 incr:  6 dt:0.2      t:1.2         
       iter:  1 | R |/| Fext |= 9.330e-16  | Fext |=153.517

cyc:  1 seq:  1 incr:  7 dt:0.2      t:1.4         
       iter:  1 | R |/| Fext |= 9.758e-16  | Fext |=142.145

cyc:  1 seq:  1 incr:  8 dt:0.2      t:1.6         
       iter:  1 | R |/| Fext |= 1.054e-15  | Fext |=130.773

cyc:  1 seq:  1 incr:  9 dt:0.2      t:1.8         
       iter:  1 | R |/| Fext |= 8.726e-16  | Fext |=119.402

cyc:  1 seq:  1 incr: 10 dt:0.2      t:2           
       iter:  1 | R |/| Fext |= 1.002e-15  | Fext |=108.030


++++++++++++++++++++++  end of Z++  ++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                     CPU time  Wall-clock
  Time CPU Total                  =      0.34      0.4487
  Time Problem Loading            =         0    0.008939
  Time Loading nodes              =         0    0.001698
  Time Loading elements           =      0.01    0.002031
  Time Read nset                  =         0   0.0003955
  Time Read bset                  =         0   0.0002871
  Time Mesh connections           =         0   0.0001209
  Time Mesh create dof            =         0    0.000644
  Time Sparse matrix profile      =         0    0.002559
  Time Mumps profile              =      0.01    0.003146
  Time Mumps analyze              =      0.01    0.002315
  Time Compute_internal_reac      =      0.13      0.1529
  Time Output                     =      0.07     0.06614
  Time Execution                  =      0.32      0.3316
  Time Mumps solver               =       0.1     0.09401
  Time Mumps factorization        =      0.09     0.08867
  Time Mumps solutions            =      0.01    0.003846
  Mumps analyze calls             =  1
  Compute_internal_reac calls     =  21
  Total Iterations                =  10
  Mumps factorization calls       =  10
  Mumps solutions calls           =  10
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

