/*!
* \file   IsotropicLinearHardeningMises.cxx
* \brief  this file implements the IsotropicLinearHardeningMises Behaviour.
*         File generated by tfel version 4.0.0
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/IsotropicLinearHardeningMisesBehaviourData.hxx"
#include"TFEL/Material/IsotropicLinearHardeningMisesIntegrationData.hxx"
#include"TFEL/Material/IsotropicLinearHardeningMises.hxx"

namespace tfel::material{

IsotropicLinearHardeningMisesParametersInitializer&
IsotropicLinearHardeningMisesParametersInitializer::get()
{
static IsotropicLinearHardeningMisesParametersInitializer i;
return i;
}

IsotropicLinearHardeningMisesParametersInitializer::IsotropicLinearHardeningMisesParametersInitializer()
{
this->young = 200000;
this->nu = 0.2;
this->H = 100;
this->s0 = 10;
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.7976931348623e+308;
// Reading parameters from a file
IsotropicLinearHardeningMisesParametersInitializer::readParameters(*this,"IsotropicLinearHardeningMises-parameters.txt");
}

void
IsotropicLinearHardeningMisesParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("YoungModulus",key)==0){
this->young = v;
} else if(::strcmp("PoissonRatio",key)==0){
this->nu = v;
} else if(::strcmp("HardeningSlope",key)==0){
this->H = v;
} else if(::strcmp("YieldStrength",key)==0){
this->s0 = v;
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else {
tfel::raise("IsotropicLinearHardeningMisesParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

double
IsotropicLinearHardeningMisesParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"IsotropicLinearHardeningMisesParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

void
IsotropicLinearHardeningMisesParametersInitializer::readParameters(IsotropicLinearHardeningMisesParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"IsotropicLinearHardeningMisesParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("YoungModulus"==tokens[0]){
pi.young = IsotropicLinearHardeningMisesParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("PoissonRatio"==tokens[0]){
pi.nu = IsotropicLinearHardeningMisesParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("HardeningSlope"==tokens[0]){
pi.H = IsotropicLinearHardeningMisesParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("YieldStrength"==tokens[0]){
pi.s0 = IsotropicLinearHardeningMisesParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = IsotropicLinearHardeningMisesParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = IsotropicLinearHardeningMisesParametersInitializer::getDouble(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace tfel::material

