#! /bin/bash


###### 2D #######################################
cd Modules/Sorbonne/StationaryNS/

#for nev in `seq 1 20`;
#do
#done

###NIRB Greedy algorithm FreeFem files
nev=2
python3 NirbGreedyOffline.py $nev
python3 NirbGreedyOnline.py 

###NIRB POD algorithm VTU files

python3 NirbPodOffline.py
python3 NirbPodOnline.py 


###### 3D #######################################"
cd ../3Dcase/

###NIRB Greedy algorithm

#interpolation Basictools with VTU files
python3 NirbGreedyOffline_3D.py $nev
python3 NirbGreedyOnline_3D.py 


