
-------------------------------------------------------------
| Z-set version 9.0.1            compiled 2018-12-11 by val |
|                                SVN revision:17246M        |
|                                                           |
| MINES ParisTech                www.mines-paristech.fr     |
| ONERA                          www.onera.fr               |
|                                                           |
| Website                        www.zset-software.com      |
-------------------------------------------------------------

Process Id (PID)         : 13473
Process parent Id (PPID) : 36216
Hostname                 : rosetta-viz01

Problem name: cube

============================================================
Zebulon 9.0 checking out license for fem

 checkout of license 2/500 for product:fem
 license expires in 202 days
============================================================

key: init_dof_value
key: mesh
key: resolution
key: bc
key: material
key: table
key: output

Done loading cube.geof
Number of global DOFs: 676

Number of elements              : 625
Total number of dof             : 676
Estimated memory needed (KB)    : 407

seq:  1 incr:  1 dt:100      t:100         
 iter:  1 | R |/| Fext |= 5.402e-16  | Fext |=124916.

seq:  1 incr:  2 dt:100      t:200         
 iter:  1 | R |/| Fext |= 5.132e-16  | Fext |=70853.6

seq:  1 incr:  3 dt:100      t:300         
 iter:  1 | R |/| Fext |= 4.918e-16  | Fext |=53462.3

seq:  1 incr:  4 dt:100      t:400         
 iter:  1 | R |/| Fext |= 5.899e-16  | Fext |=45090.8

seq:  1 incr:  5 dt:100      t:500         
 iter:  1 | R |/| Fext |= 5.911e-16  | Fext |=39792.3

seq:  1 incr:  6 dt:100      t:600         
 iter:  1 | R |/| Fext |= 7.153e-16  | Fext |=35962.1

seq:  1 incr:  7 dt:100      t:700         
 iter:  1 | R |/| Fext |= 8.109e-16  | Fext |=33005.7

seq:  1 incr:  8 dt:100      t:800         
 iter:  1 | R |/| Fext |= 9.437e-16  | Fext |=30632.1

seq:  1 incr:  9 dt:100      t:900         
 iter:  1 | R |/| Fext |= 9.911e-16  | Fext |=28672.6

seq:  1 incr: 10 dt:100      t:1000        
 iter:  1 | R |/| Fext |= 1.045e-15  | Fext |=27019.9


++++++++++++++++++++++  end of Z++  ++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                     CPU time  Wall-clock
  Time CPU Total                  =      0.28      0.3736
  Time Problem Loading            =      0.01    0.008166
  Time Loading nodes              =         0    0.002116
  Time Loading elements           =         0    0.002716
  Time Read nset                  =         0   8.392e-05
  Time Read bset                  =         0   0.0002038
  Time Mesh connections           =         0    0.000226
  Time Mesh create dof            =         0   0.0004609
  Time Sparse matrix profile      =         0    0.000541
  Time Mumps profile              =         0    0.001813
  Time Mumps analyze              =         0    0.001281
  Time Output                     =      0.05     0.05187
  Time Execution                  =      0.26      0.2769
  Time Compute_internal_reac      =      0.17      0.1795
  Time Mumps solver               =      0.03     0.02354
  Time Mumps factorization        =      0.01     0.01671
  Time Mumps solutions            =      0.02    0.006443
  Mumps analyze calls             =  1
  Total Iterations                =  10
  Compute_internal_reac calls     =  20
  Mumps factorization calls       =  10
  Mumps solutions calls           =  10
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

