
-------------------------------------------------------------
| Z-set version 9.0.1            compiled 2018-12-11 by val |
|                                SVN revision:17246M        |
|                                                           |
| MINES ParisTech                www.mines-paristech.fr     |
| ONERA                          www.onera.fr               |
|                                                           |
| Website                        www.zset-software.com      |
-------------------------------------------------------------

Process Id (PID)         : 38407
Process parent Id (PPID) : 30812
Hostname                 : rosetta-viz01

Problem name: cube

============================================================
Zebulon 9.0 checking out license for fem

 checkout of license 99/500 for product:fem
 license expires in 201 days
============================================================

key: init_dof_value
key: mesh
key: resolution
key: bc
key: material
key: table
key: output

Done loading cube.geof
Number of global DOFs: 676

Number of elements              : 625
Total number of dof             : 676
Estimated memory needed (KB)    : 407

seq:  1 incr:  1 dt:200      t:200         
 iter:  1 | R |/| Fext |= 1.032e-15  | Fext |=102040.

seq:  1 incr:  2 dt:200      t:400         
 iter:  1 | R |/| Fext |= 1.089e-15  | Fext |=49503.1

seq:  1 incr:  3 dt:200      t:600         
 iter:  1 | R |/| Fext |= 1.296e-15  | Fext |=37425.5

seq:  1 incr:  4 dt:200      t:800         
 iter:  1 | R |/| Fext |= 1.605e-15  | Fext |=31303.9

seq:  1 incr:  5 dt:200      t:1000        
 iter:  1 | R |/| Fext |= 1.850e-15  | Fext |=27308.5


++++++++++++++++++++++  end of Z++  ++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                     CPU time  Wall-clock
  Time CPU Total                  =      0.16      0.1952
  Time Problem Loading            =      0.01     0.00667
  Time Loading nodes              =         0    0.002075
  Time Loading elements           =         0    0.002666
  Time Read nset                  =         0   5.507e-05
  Time Read bset                  =         0    0.000164
  Time Mesh connections           =         0    0.000227
  Time Mesh create dof            =         0   0.0004349
  Time Sparse matrix profile      =         0   0.0004392
  Time Mumps profile              =         0    0.001137
  Time Mumps analyze              =         0   0.0008941
  Time Output                     =      0.03     0.03281
  Time Execution                  =      0.13      0.1493
  Time Compute_internal_reac      =      0.09     0.09699
  Time Mumps solver               =         0     0.01194
  Time Mumps factorization        =         0    0.008436
  Time Mumps solutions            =         0    0.003313
  Mumps analyze calls             =  1
  Total Iterations                =  5
  Compute_internal_reac calls     =  10
  Mumps factorization calls       =  5
  Mumps solutions calls           =  5
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

