name: CI

on:
  push:
    branches:
      - 'cemosis'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches:
      - 'cemosis'
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
#docs:
#  runs-on: ubuntu-latest
#  if: "!contains(github.event.head_commit.message, 'doc skip')"
#  steps:
#  - uses: buildkite/trigger-pipeline-action@v1.2.0
#    env:
#      BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
#      PIPELINE: "feelpp/cemosis-docs"
#      COMMIT: "HEAD"
#      BRANCH: "master"
#      MESSAGE: ":github: Triggered from a GitHub Action by brain Project"
  build:
    runs-on: self-ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: Check Build, Install, Run
    steps:
    - uses: actions/checkout@v2
    - name: Configure Mordicus
      run: |
        ls -lrt
        cmake --version
        cmake --preset install
    - name: Build Mordicus
      run:  cmake --build --preset install
    - name: Add Python Dependencies
      run: |
        pip install --upgrade pip
        pip install -r ./src/poc-1/requirements.txt
    - name: Add PYTHONPATH
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE/src/poc-1/src/:$HOME/.local/lib/python3.8/site-packages/" >> $GITHUB_ENV
        ls -lrt src/poc-1/src
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE/src/poc-1/src
    - name: Run PyTest
      run: $HOME/.local/bin/pytest --ignore Modules/Safran
      working-directory: src/poc-1/tests
    - name: Run Mordicus Core Coverage
      run: |
        echo '... NonRegression tests on Core ended'
        mkdir -p pages/coverageReportCore
        echo 'Starting coverage report on Core...'
        $HOME/.local/bin/pytest --cov=../../src/Mordicus/Core --cov-report=html:../../../../pages/coverageReportCore && cd -
      working-directory: src/poc-1/tests/Core
    - name: Upload 
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: mordicus-artifacts
        # Directory containing files to upload
        path: build/install/assets/mordicus-*

  build-docker:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    name: Check Build, Install, Run on Docker
    steps:
    - uses: actions/checkout@v2
    - name: Install Mordicus C++
      run: |
        apt-get update
        apt-get -y install apt-transport-https ca-certificates gnupg software-properties-common wget
        add-apt-repository  'deb [trusted=yes] http://apt.feelpp.org/debian/bullseye bullseye latest' && add-apt-repository  'deb http://deb.debian.org/debian bullseye-backports main'
        wget -O - http://apt.feelpp.org/apt.gpg | apt-key add - && apt-get update 
        apt-get -y install python3-pip python3-venv gcc clang python3-dev libopenmpi-dev make libeigen3-dev python3-lxml python3-feelpp 
        apt-get -y install -t bullseye-backports  cmake
    - name: Configure Mordicus
      run: |
        ls -lrt
        cmake --version
        cmake --preset install
        cmake --build --preset install
        ctest --preset install
    - name: Build Mordicus C++
      run:  cmake --build --preset install
   
    - name: Test Mordicus C++
      run:  ctest --preset install
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Mordicus Python Dependencies
      run: |
        pip install -r ./src/poc-1/requirements.txt
    - name: Configure Mordicus Python
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE/src/poc-1/src/:$PYTHONPATH" >> $GITHUB_ENV
        ls -lrt src/poc-1/src
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE/src/poc-1/src
    - name: Test Mordicus Python
      run: pytest --ignore Modules/Safran
      working-directory: src/poc-1/tests
    - name: Run Mordicus Core Coverage
      run: |
        echo '... NonRegression tests on Core ended'
        mkdir -p pages/coverageReportCore
        echo 'Starting coverage report on Core...'
        pytest --cov=../../src/Mordicus/Core --cov-report=html:../../../../pages/coverageReportCore && cd -
      working-directory: src/poc-1/tests/Core

  deliver:
    runs-on: ubuntu-20.04
    needs: build
    # needs: check
    name: Docker Build, Tag, Push

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    
    - name: Download 
      uses: actions/download-artifact@v2
      with:
        # Artifact name
        name: mordicus-artifacts
        path: artifacts/
    -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/feelpp/mordicus
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1        
    - 
      name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - 
      name: Build container image
      uses: docker/build-push-action@v2
      with: 
        push: ${{ github.event_name != 'pull_request' }}
        context: artifacts
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ./Dockerfile