name: CI

on:
  push:
    branches:
      - 'cemosis'
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  docs:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'docs skip')"
    name: Build Docs Website
    steps:
    - uses: actions/checkout@v2
    - name: Install sphinx
      run: |
        pip install --upgrade pip
        pip install -r ./src/poc-1/requirements.txt
        pip install -U sphinx
        echo "PYTHONPATH=$GITHUB_WORKSPACE/src/poc-1/src" >> $GITHUB_ENV
    - name: Run Sphinx
      run: python setup.py build_sphinx
      working-directory: src/poc-1/
    - name: Deploy Sphinx 
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: src/poc-1/doc/_build/html 